# Generated by Django 4.2.4 on 2023-09-07 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_user_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='verification_code',
            field=models.CharField(blank=True, max_length=10, null=True, unique=True, verbose_name='Код верификации'),
        ),
    ]
