# Generated by Django 4.2.4 on 2023-08-18 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogentry',
            name='slug',
            field=models.SlugField(max_length=150, verbose_name='slug'),
        ),
    ]
