# Generated by Django 4.2.4 on 2023-08-18 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_blogentry_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogentry',
            name='title',
            field=models.CharField(max_length=100, unique=True, verbose_name='Заголовок'),
        ),
    ]
