# Generated by Django 4.2.4 on 2023-08-08 10:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ('name',), 'verbose_name': 'Категория', 'verbose_name_plural': 'Категории'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ('change_date', 'name'), 'verbose_name': 'Продукт', 'verbose_name_plural': 'Продукты'},
        ),
    ]
