# Generated by Django 4.2.4 on 2023-08-16 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0010_alter_blogentry_is_published'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogentry',
            name='image',
            field=models.ImageField(blank=True, default='default.jpg', null=True, upload_to='blog/', verbose_name='Изображение'),
        ),
    ]
