# Generated by Django 4.2.4 on 2023-08-16 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0011_alter_blogentry_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogentry',
            name='image',
            field=models.ImageField(blank=True, default='blog/default.jpg', null=True, upload_to='blog/', verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, default='products/default.png', null=True, upload_to='products/', verbose_name='Изображение'),
        ),
    ]
