# Generated by Django 4.2.4 on 2023-08-29 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0015_version'),
    ]

    operations = [
        migrations.AlterField(
            model_name='version',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Название версии'),
        ),
        migrations.AlterField(
            model_name='version',
            name='number',
            field=models.PositiveSmallIntegerField(verbose_name='Номер версии'),
        ),
        migrations.AlterField(
            model_name='version',
            name='status',
            field=models.BooleanField(default=True, verbose_name='Активная версия'),
        ),
    ]
